# Generated by Django 4.1.2 on 2022-11-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
                ('prueba', models.CharField(max_length=100)),
                ('emerg_contacto', models.CharField(max_length=100)),
                ('emerg_llamar', models.IntegerField()),
            ],
        ),
    ]
